/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.som.telas;

/**
 *
 * @author vickb
 */
import java.sql.*;
import br.com.som.dal.ModuloConexao;
import javax.swing.JOptionPane;


public class UserSc extends javax.swing.JInternalFrame {

    Connection conexao = null; // Variavel do modulo de conexão
    PreparedStatement pst = null; // Manipular instruções SQL
    ResultSet rs = null; // Exibe os resultados das instruções SQL
    /**
     * Creates new form UserSc
     */
    public UserSc() {
        initComponents();
        conexao = ModuloConexao.conectar();
    }
    
    private void limpar(){
                txtUsId.setText(null);
                txtUsNome.setText(null);
                txtUsFon.setText(null);
                txtUsLog.setText(null);
                txtUsPsw.setText(null);
                
    }
    
    private void consultar(){
        String sql = "select * from usuarios where iduser=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,txtUsId.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtUsNome.setText(rs.getString(2));
                txtUsFon.setText(rs.getString(3));
                txtUsLog.setText(rs.getString(4));
                txtUsPsw.setText(rs.getString(5));
                cbxUsPerf.setSelectedItem(rs.getString(6));
                
            } else { 
                JOptionPane.showMessageDialog(null,"Usuário não encontrado.");
                txtUsNome.setText(null);
                txtUsFon.setText(null);
                txtUsLog.setText(null);
                txtUsPsw.setText(null);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);// caso haja um erro
            // retorna numa janela
        }
    }
    
    private void adicionar(){
    String sql="insert into usuarios (iduser, usuario, phone, login, senhar, perfil) values(?,?,?,?,?,?)";
        try {
            pst=conexao.prepareStatement(sql);
            pst.setString(1, txtUsId.getText());
            pst.setString(2, txtUsNome.getText());
            pst.setString(3, txtUsFon.getText());
            pst.setString(4, txtUsLog.getText());
            pst.setString(5, txtUsPsw.getText());
            pst.setString(6, cbxUsPerf.getSelectedItem().toString());
            
            if (txtUsId.getText().isEmpty() || txtUsNome.getText().isEmpty() || txtUsLog.getText().isEmpty() || txtUsPsw.getText().isEmpty()){
                 JOptionPane.showMessageDialog(null,"Preencha todos os campos obrigatórios");
            }
            
            // Atualizar a tabela com o form
           int adicionado = pst.executeUpdate(); // variável para confirmar a adesão
           if(adicionado > 0){
               JOptionPane.showMessageDialog(null, " Usuário cadastrado com sucesso!");
               limpar();
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);// caso haja um erro
            // retorna numa janela
        }
} 
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsId = new javax.swing.JTextField();
        txtUsNome = new javax.swing.JTextField();
        txtUsLog = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxUsPerf = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtUsFon = new javax.swing.JFormattedTextField();
        btnUsCreate = new javax.swing.JButton();
        btnUsRead = new javax.swing.JButton();
        btnUsUpdt = new javax.swing.JButton();
        btnUsDel = new javax.swing.JButton();
        txtUsPsw = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Usuários");
        setPreferredSize(new java.awt.Dimension(900, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("*Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("*Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("*Senha");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("*Login");

        txtUsId.setText("              ");
        txtUsId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsIdActionPerformed(evt);
            }
        });

        txtUsNome.setText("              ");
        txtUsNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsNomeActionPerformed(evt);
            }
        });

        txtUsLog.setText("              ");
        txtUsLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsLogActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Perfil");

        cbxUsPerf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "user", " " }));
        cbxUsPerf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUsPerfActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Telefone");

        try {
            txtUsFon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtUsFon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsFonActionPerformed(evt);
            }
        });

        btnUsCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/som/icones/create.png"))); // NOI18N
        btnUsCreate.setToolTipText("Adicionar Usuário");
        btnUsCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsCreateActionPerformed(evt);
            }
        });

        btnUsRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/som/icones/consultar.png"))); // NOI18N
        btnUsRead.setToolTipText("Consultar Usuários");
        btnUsRead.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsReadActionPerformed(evt);
            }
        });

        btnUsUpdt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/som/icones/update.png"))); // NOI18N
        btnUsUpdt.setToolTipText("Atualizar ");
        btnUsUpdt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnUsDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/som/icones/delete.png"))); // NOI18N
        btnUsDel.setToolTipText("Excluir Usuário");
        btnUsDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsDelActionPerformed(evt);
            }
        });

        txtUsPsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsPswActionPerformed(evt);
            }
        });

        jLabel7.setText("*Campos Obrigatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addComponent(btnUsCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtUsPsw, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsLog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxUsPerf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsFon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(133, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnUsRead, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUsUpdt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUsDel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnUsCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUsRead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUsUpdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnUsDel)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtUsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtUsLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtUsPsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtUsFon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxUsPerf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        setBounds(0, 0, 691, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsIdActionPerformed

    private void txtUsNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsNomeActionPerformed

    private void txtUsLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsLogActionPerformed

    private void cbxUsPerfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUsPerfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxUsPerfActionPerformed

    private void txtUsFonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsFonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsFonActionPerformed

    private void btnUsReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsReadActionPerformed
        // Chamar o met. consultar.
        consultar();
    }//GEN-LAST:event_btnUsReadActionPerformed

    private void btnUsCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsCreateActionPerformed
        adicionar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsCreateActionPerformed

    private void txtUsPswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsPswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsPswActionPerformed

    private void btnUsDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsDelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUsCreate;
    private javax.swing.JButton btnUsDel;
    private javax.swing.JButton btnUsRead;
    private javax.swing.JButton btnUsUpdt;
    private javax.swing.JComboBox cbxUsPerf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField txtUsFon;
    private javax.swing.JTextField txtUsId;
    private javax.swing.JTextField txtUsLog;
    private javax.swing.JTextField txtUsNome;
    private javax.swing.JTextField txtUsPsw;
    // End of variables declaration//GEN-END:variables
}
